

; ---------------------------------------------------------------------------

; battlescene

; $0 Transparent

; $1-$1F HP/MP bars

VDPTILE_SPACE: equ $20
VDPTILE_EXCLAMATION_MARK: equ $21
VDPTILE_QUOTATION_MARK: equ $22
VDPTILE_NUMBER_SIGN: equ $23
VDPTILE_PRICE_STRING: equ $24
VDPTILE_PERCENT_SIGN: equ $25
VDPTILE_AMPERSAND: equ $26
VDPTILE_APOSTROPHE: equ $27
VDPTILE_OPENING_ROUND_BRACKET: equ $28
VDPTILE_CLOSING_ROUND_BRACKET: equ $29
VDPTILE_MULTIPLICATION_SIGN: equ $2A
VDPTILE_PLUS_SIGN: equ $2B
VDPTILE_COMMA: equ $2C
VDPTILE_MINUS_SIGN: equ $2D
VDPTILE_DOT: equ $2E
VDPTILE_SLASH: equ $2F
VDPTILE_NUMBER_0: equ $30
VDPTILE_NUMBER_1: equ $31
VDPTILE_NUMBER_2: equ $32
VDPTILE_NUMBER_3: equ $33
VDPTILE_NUMBER_4: equ $34
VDPTILE_NUMBER_5: equ $35
VDPTILE_NUMBER_6: equ $36
VDPTILE_NUMBER_7: equ $37
VDPTILE_NUMBER_8: equ $38
VDPTILE_NUMBER_9: equ $39
VDPTILE_COLON: equ $3A
VDPTILE_: equ $3B
VDPTILE_STATUSEFFECT_SILENCE1: equ $3C
VDPTILE_EQUALS_SIGN: equ $3D
VDPTILE_STATUSEFFECT_SILENCE2: equ $3E
VDPTILE_QUESTION_MARK: equ $3F
VDPTILE_COPYRIGHT_SIGN: equ $40
VDPTILE_UPPERCASE_A: equ $41
VDPTILE_UPPERCASE_B: equ $42
VDPTILE_UPPERCASE_C: equ $43
VDPTILE_UPPERCASE_D: equ $44
VDPTILE_UPPERCASE_E: equ $45
VDPTILE_UPPERCASE_F: equ $46
VDPTILE_UPPERCASE_G: equ $47
VDPTILE_UPPERCASE_H: equ $48
VDPTILE_UPPERCASE_I: equ $49
VDPTILE_UPPERCASE_J: equ $4A
VDPTILE_UPPERCASE_K: equ $4B
VDPTILE_UPPERCASE_L: equ $4C
VDPTILE_UPPERCASE_M: equ $4D
VDPTILE_UPPERCASE_N: equ $4E
VDPTILE_UPPERCASE_O: equ $4F
VDPTILE_UPPERCASE_P: equ $50
VDPTILE_UPPERCASE_Q: equ $51
VDPTILE_UPPERCASE_R: equ $52
VDPTILE_UPPERCASE_S: equ $53
VDPTILE_UPPERCASE_T: equ $54
VDPTILE_UPPERCASE_U: equ $55
VDPTILE_UPPERCASE_V: equ $56
VDPTILE_UPPERCASE_W: equ $57
VDPTILE_UPPERCASE_X: equ $58
VDPTILE_UPPERCASE_Y: equ $59
VDPTILE_UPPERCASE_Z: equ $5A
VDPTILE_: equ $5B
VDPTILE_RED_DOT: equ $5C
VDPTILE_: equ $5D
VDPTILE_GREEN_DOT: equ $5E
VDPTILE_UNDERSCORE: equ $5F
VDPTILE_SPACE2: equ $60
VDPTILE_LOWERCASE_A: equ $61
VDPTILE_LOWERCASE_B: equ $62
VDPTILE_LOWERCASE_C: equ $63
VDPTILE_LOWERCASE_D: equ $64
VDPTILE_LOWERCASE_E: equ $65
VDPTILE_LOWERCASE_F: equ $66
VDPTILE_LOWERCASE_G: equ $67
VDPTILE_LOWERCASE_H: equ $68
VDPTILE_LOWERCASE_I: equ $69
VDPTILE_LOWERCASE_J: equ $6A
VDPTILE_LOWERCASE_K: equ $6B
VDPTILE_LOWERCASE_L: equ $6C
VDPTILE_LOWERCASE_M: equ $6D
VDPTILE_LOWERCASE_N: equ $6E
VDPTILE_LOWERCASE_O: equ $6F
VDPTILE_LOWERCASE_P: equ $70
VDPTILE_LOWERCASE_Q: equ $71
VDPTILE_LOWERCASE_R: equ $72
VDPTILE_LOWERCASE_S: equ $73
VDPTILE_LOWERCASE_T: equ $74
VDPTILE_LOWERCASE_U: equ $75
VDPTILE_LOWERCASE_V: equ $76
VDPTILE_LOWERCASE_W: equ $77
VDPTILE_LOWERCASE_X: equ $78
VDPTILE_LOWERCASE_Y: equ $79
VDPTILE_LOWERCASE_Z: equ $7A
VDPTILE_SPACE3: equ $7B
VDPTILE_SPACE4: equ $7C
VDPTILE_PROMOTION_SIGN: equ $7D
VDPTILE_INPARTY_SIGN: equ $7E
VDPTILE_EQUIPPED_SIGN: equ $7F
VDPTILE_CORNER: equ $80
VDPTILE_H_BORDER: equ $81
VDPTILE_: equ $82
VDPTILE_: equ $83
VDPTILE_V_ARROW: equ $84
VDPTILE_H_ARROW: equ $85
VDPTILE_HYPHEN: equ $86
VDPTILE_SPACE5: equ $87
VDPTILE_SPACE6: equ $88
VDPTILE_SPACE7: equ $89
VDPTILE_SPACE8: equ $8A
VDPTILE_SPACE9: equ $8B
VDPTILE_SPACE10: equ $8C
VDPTILE_SPACE11: equ $8D
VDPTILE_SPACE12: equ $8E
VDPTILE_ORANGE_EQUALS_SIGN: equ $8F
VDPTILE_V_BORDER: equ $90
VDPTILE_ORANGE_EXCLAMATION_MARK: equ $91
VDPTILE_ORANGE_QUOTATION_MARK: equ $92
VDPTILE_ORANGE_NUMBER_SIGN: equ $93
VDPTILE_ORANGE_COLON: equ $94
VDPTILE_ORANGE_PERCENT_SIGN: equ $95
VDPTILE_ORANGE_AMPERSAND: equ $96
VDPTILE_ORANGE_APOSTROPHE: equ $97
VDPTILE_ORANGE_OPENING_ROUND_BRACKET: equ $98
VDPTILE_ORANGE_CLOSING_ROUND_BRACKET: equ $99
VDPTILE_ORANGE_MULTIPLICATION_SIGN: equ $9A
VDPTILE_ORANGE_PLUS_SIGN: equ $9B
VDPTILE_ORANGE_COMMA: equ $9C
VDPTILE_ORANGE_MINUS_SIGN: equ $9D
VDPTILE_ORANGE_DOT: equ $9E
VDPTILE_ORANGE_SLASH: equ $9F
VDPTILE_ORANGE_QUESTION_MARK: equ $A0
VDPTILE_ORANGE_UPPERCASE_A: equ $A1
VDPTILE_ORANGE_UPPERCASE_B: equ $A2
VDPTILE_ORANGE_UPPERCASE_C: equ $A3
VDPTILE_ORANGE_UPPERCASE_D: equ $A4
VDPTILE_ORANGE_UPPERCASE_E: equ $A5
VDPTILE_ORANGE_UPPERCASE_F: equ $A6
VDPTILE_ORANGE_UPPERCASE_G: equ $A7
VDPTILE_ORANGE_UPPERCASE_H: equ $A8
VDPTILE_ORANGE_UPPERCASE_I: equ $A9
VDPTILE_ORANGE_UPPERCASE_J: equ $AA
VDPTILE_ORANGE_UPPERCASE_K: equ $AB
VDPTILE_ORANGE_UPPERCASE_L: equ $AC
VDPTILE_ORANGE_UPPERCASE_M: equ $AD
VDPTILE_ORANGE_UPPERCASE_N: equ $AE
VDPTILE_ORANGE_UPPERCASE_O: equ $AF
VDPTILE_ORANGE_UPPERCASE_P: equ $B0
VDPTILE_ORANGE_UPPERCASE_Q: equ $B1
VDPTILE_ORANGE_UPPERCASE_R: equ $B2
VDPTILE_ORANGE_UPPERCASE_S: equ $B3
VDPTILE_ORANGE_UPPERCASE_T: equ $B4
VDPTILE_ORANGE_UPPERCASE_U: equ $B5
VDPTILE_ORANGE_UPPERCASE_V: equ $B6
VDPTILE_ORANGE_UPPERCASE_W: equ $B7
VDPTILE_ORANGE_UPPERCASE_X: equ $B8
VDPTILE_ORANGE_UPPERCASE_Y: equ $B9
VDPTILE_ORANGE_UPPERCASE_Z: equ $BA
VDPTILE_ORANGE_NUMBER_0: equ $BB
VDPTILE_ORANGE_NUMBER_1: equ $BC
VDPTILE_ORANGE_NUMBER_2: equ $BD
VDPTILE_ORANGE_NUMBER_3: equ $BE
VDPTILE_ORANGE_NUMBER_4: equ $BF
VDPTILE_ORANGE_UNDERSCORE: equ $C0
VDPTILE_ORANGE_LOWERCASE_A: equ $C1
VDPTILE_ORANGE_LOWERCASE_B: equ $C2
VDPTILE_ORANGE_LOWERCASE_C: equ $C3
VDPTILE_ORANGE_LOWERCASE_D: equ $C4
VDPTILE_ORANGE_LOWERCASE_E: equ $C5
VDPTILE_ORANGE_LOWERCASE_F: equ $C6
VDPTILE_ORANGE_LOWERCASE_G: equ $C7
VDPTILE_ORANGE_LOWERCASE_H: equ $C8
VDPTILE_ORANGE_LOWERCASE_I: equ $C9
VDPTILE_ORANGE_LOWERCASE_J: equ $CA
VDPTILE_ORANGE_LOWERCASE_K: equ $CB
VDPTILE_ORANGE_LOWERCASE_L: equ $CC
VDPTILE_ORANGE_LOWERCASE_M: equ $CD
VDPTILE_ORANGE_LOWERCASE_N: equ $CE
VDPTILE_ORANGE_LOWERCASE_O: equ $CF
VDPTILE_ORANGE_LOWERCASE_P: equ $D0
VDPTILE_ORANGE_LOWERCASE_Q: equ $D1
VDPTILE_ORANGE_LOWERCASE_R: equ $D2
VDPTILE_ORANGE_LOWERCASE_S: equ $D3
VDPTILE_ORANGE_LOWERCASE_T: equ $D4
VDPTILE_ORANGE_LOWERCASE_U: equ $D5
VDPTILE_ORANGE_LOWERCASE_V: equ $D6
VDPTILE_ORANGE_LOWERCASE_W: equ $D7
VDPTILE_ORANGE_LOWERCASE_X: equ $D8
VDPTILE_ORANGE_LOWERCASE_Y: equ $D9
VDPTILE_ORANGE_LOWERCASE_Z: equ $DA
VDPTILE_ORANGE_NUMBER_5: equ $DB
VDPTILE_ORANGE_NUMBER_6: equ $DC
VDPTILE_ORANGE_NUMBER_7: equ $DD
VDPTILE_ORANGE_NUMBER_8: equ $DE
VDPTILE_ORANGE_NUMBER_9: equ $DF

; $E0-$ED more HP/MP bars

VDPTILE_STATUSEFFECT_POISON1: equ $EE
VDPTILE_STATUSEFFECT_POISON2: equ $EF

VDPTILE_SPELL_LEVEL1: equ $F0
VDPTILE_SPELL_LEVEL2: equ $F1
VDPTILE_SPELL_LEVEL3: equ $F2
VDPTILE_SPELL_LEVEL4: equ $F3
VDPTILE_SPELL_LEVEL5: equ $F4
VDPTILE_SPELL_LEVEL6: equ $F5
VDPTILE_SPELL_LEVEL7: equ $F6
VDPTILE_SPELL_LEVEL8: equ $F7

VDPTILE_SPACE13: equ $F8
VDPTILE_PORTRAIT_CORNER: equ $F9
VDPTILE_PORTRAIT_HORIZONTAL: equ $FA
VDPTILE_PORTRAIT_VERTICAL: equ $FB

VDPTILE_STATUSEFFECT_SLEEP1: equ $FC
VDPTILE_STATUSEFFECT_SLEEP2: equ $FD
VDPTILE_STATUSEFFECT_CURSE1: equ $FE
VDPTILE_STATUSEFFECT_CURSE2: equ $FF

; $100-$27F Background

; $280-$3FF Enemy Battlesprite

; $400-$51F Ally Battlesprite

; $520-$55F Weapon

; $560-$58F Ground

; $590-$59F [unused] duplicate background piece

; $5A0-5BF [unused]

; $5C0-$67F Spell Graphics

; $680-$6F0
VDPTILE_TEXTBOX_CORNER: equ $680
VDPTILE_TEXTBOX_HORIZONTAL: equ $681
VDPTILE_TEXTBOX_VERTICAL: equ $685
VDPTILE_TEXTBOX_BODY: equ $689 ; 26 tiles per line

; $6F1-$7FF [unused]

; ---------------------------------------------------------------------------

; exploration

; $0 Transparent

; $

; $

; $

; $

; $

; $

; $

VDPTILE_: equ $

